server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: event_service
          uri: lb://event-service
          predicates:
            - name: Path
              args:
                patterns:
                  - /admin/categories/**
                  - /categories/**
                  - /admin/compilations/**
                  - /compilations/**
                  - /admin/events/**
                  - /users/{userId}/events/**
                  - /events/**

        - id: rating_service
          uri: lb://rating-service
          predicates:
            - Path=/events/{eventId}/rating, /users/{userId}/events/{eventId}/rating

        - id: request_service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, /request/**

        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**